//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNwpf1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DN_wpf1Entities : DbContext
    {
        private static DN_wpf1Entities _context;

        public DN_wpf1Entities()
            : base("name=DN_wpf1Entities")
        {
        }
    

        public static DN_wpf1Entities GetContext()
        {
            if (_context == null)
                _context = new DN_wpf1Entities();

            return _context;
        }



        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ListRight> ListRight { get; set; }
        public virtual DbSet<Rigths> Rigths { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UsersRoles> UsersRoles { get; set; }
    }
}
