//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNwpf1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListRight
    {
        public int id { get; set; }
        public int id_user { get; set; }
        public int id_right { get; set; }
    }
}
